import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,createRequest,transition,saveDecision,loadState} from '../public/app/model.mjs';
import {saveReflection,rewardAssessment,submitReward,reviewReward,validateReflection,followupFor} from '../public/app/reflection.mjs';
const now=new Date('2026-09-29T01:00:00Z');
const step=(s,a,e={})=>transition(s,a,e,'테스트 확인',now);
const request=()=>createRequest(initialState(),{start:'2026-10-01',end:'2026-10-04'},now);
function active(){let s=step(request(),'review');s=step(s,'secure',{terms:true,buffer:true});s=step(s,'confirm',{approved:true,amount:true,reservation:true});return step(s,'pickup',{handoff:true});}
function completed(){let s=saveDecision(active(),{choice:'return',reason:'더 써본 다음 결정',confidence:2});s=step(s,'return');s=step(s,'receive',{air:true,pro:true});return step(s,'inspect',{air:true,pro:true});}
const answer={moment:'watch',devices:'both',condition:'same',preference:'same',detail:'screen',followup:'enough',note:''};
test('a first request requires dates only and does not invent a use case or confidence',()=>{const s=request();assert.equal(s.request.task,null);assert.equal(s.request.beforeConfidence,null);assert.equal(s.request.status,'requested');});
test('reflections cannot be created before handoff',()=>assert.throws(()=>saveReflection(request(),answer,now),/기기를 받은/));
test('no difference is valid without text, and old data is not changed',()=>{const base=active(),s=saveReflection(base,answer,now);assert.equal(s.reflections.length,1);assert.deepEqual(s.reflections[0].flags,[]);assert.equal(s.reflections[0].note,'');assert.equal(base.reflections,undefined);});
test('uncertainty is valid and never a rejection flag',()=>{const s=saveReflection(active(),{...answer,preference:'unsure',detail:'unclear',followup:'time'},now);assert.deepEqual(s.reflections[0].flags,[]);});
test('negative experience remains valid; single-device context is requested without rejection',()=>{const s=saveReflection(active(),{...answer,devices:'air',preference:'difficult',followup:'unavailable'},now);assert.deepEqual(s.reflections[0].flags,['single_device']);assert.equal(s.reflections[0].preference,'difficult');});
test('inapplicable followups and impossible device/preference combinations are rejected',()=>{assert.throws(()=>saveReflection(active(),{...answer,followup:'pro'},now),/마지막 질문/);assert.throws(()=>saveReflection(active(),{...answer,devices:'air',preference:'pro',followup:'later'},now),/느낌/);});
test('context prompts follow actual answers and preserve uncertain choices',()=>{assert.ok(followupFor({...answer,condition:'different'}).options.setup);assert.ok(followupFor({...answer,preference:'unsure'}).options.none);});
test('different conditions and a changed preference are review signals only',()=>{let s=saveReflection(active(),{...answer,condition:'different',preference:'pro',followup:'setup'},now);assert.deepEqual(s.reflections[0].flags,['different_context']);s=saveReflection(s,{...answer,moment:'carry',preference:'air',detail:'weight',followup:'pro'},now);assert.deepEqual(s.reflections[1].flags,['choice_changed']);});
test('same-day duplicates do not multiply records, regardless of text length',()=>{const s=saveReflection(active(),answer,now);assert.throws(()=>saveReflection(s,{...answer,note:'긴 글로 우회'.repeat(40)},now),/이미 저장/);assert.equal(s.reflections.length,1);});
test('a later day may record the same honest experience without replacing history',()=>{const s=saveReflection(saveReflection(active(),answer,now),answer,new Date('2026-09-30T01:00:00Z'));assert.equal(s.reflections.length,2);assert.notEqual(s.reflections[0].id,s.reflections[1].id);});
test('skipping a record does not block choice or return',()=>{const s=completed();assert.equal(s.request.status,'completed');assert.equal(s.reflections,undefined);});
test('reward application waits for actual demo return/inspection status and a record',()=>{assert.throws(()=>submitReward(saveReflection(active(),answer,now),now),/반납/);assert.throws(()=>submitReward(completed(),now),/기록/);});
test('one application contains a stable snapshot and no invented amount or paid status',()=>{let s=saveReflection(completed(),answer,now);s=submitReward(s,now);assert.equal(s.rewardClaim.amount,null);assert.equal(s.rewardClaim.status,'pending_review');assert.equal(s.rewardClaim.recordIds.length,1);assert.throws(()=>submitReward(s,now),/이미 신청/);s=saveReflection(s,{...answer,moment:'carry',detail:'weight'},now);assert.equal(s.reflections.length,2);assert.equal(s.rewardClaim.recordIds.length,1);});
test('flags do not auto-reject; reviewer requests context or finishes without paying',()=>{let s=saveReflection(completed(),{...answer,devices:'pro',preference:'difficult',followup:'not_yet'},now);assert.equal(rewardAssessment(s).status,'ready');s=submitReward(s,now);assert.equal(s.rewardClaim.reviewNotes.length,1);assert.throws(()=>reviewReward(s,{result:'reviewed',reason:''},now),/맥락/);s=reviewReward(s,{result:'needs_context',reason:'다른 기기를 못 쓴 사정을 확인'},now);s=reviewReward(s,{result:'reviewed',reason:'설정이 어려웠던 경험임을 확인'},now);assert.equal(s.rewardClaim.status,'reviewed');assert.equal(s.rewardClaim.reviews.length,2);assert.equal(s.rewardClaim.amount,null);});
test('old v1 storage restores without destructive migration; new histories also restore',()=>{const old=active();assert.deepEqual(loadState({getItem:()=>JSON.stringify(old)}),old);const s=submitReward(saveReflection(completed(),answer,now),now);assert.deepEqual(loadState({getItem:()=>JSON.stringify(s)}),s);});
test('corrupt reflection history is surfaced instead of silently discarded',()=>assert.throws(()=>loadState({getItem:()=>JSON.stringify({...active(),reflections:{}})}),/원본/));
test('malformed records, incomplete advanced drafts and broken claims preserve recoverable raw data',()=>{
  const base=submitReward(saveReflection(completed(),answer,now),now);
  for(const altered of [{...base,reflections:[null]},{...base,reflectionDraft:{step:2,moment:'unknown'}},{...base,rewardClaim:{...base.rewardClaim,recordIds:['missing']}},{...base,rewardClaim:{...base.rewardClaim,reviews:[{}]}}])assert.throws(()=>loadState({getItem:()=>JSON.stringify(altered)}),/원본/);
});
